start ..\TestClient\bin\Release\TestClient.exe
start ..\TestClient\bin\Release\TestClient.exe
start ..\TestClient\bin\Release\TestClient.exe
start ..\TestClient\bin\Release\TestClient.exe
start ..\TestClient\bin\Release\TestClient.exe
start ..\TestClient\bin\Release\TestClient.exe
start ..\TestClient\bin\Release\TestClient.exe
start ..\TestClient\bin\Release\TestClient.exe
start ..\TestClient\bin\Release\TestClient.exe
start ..\TestClient\bin\Release\TestClient.exe
